In [2]:
import numpy as np


In [33]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.linspace(0, 10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

Vectors can be represented using `numpy.array`. So for example, to represent the vector:

$$
v = \begin{bmatrix} 2 \\ 3 \\ 1 \end{bmatrix}
$$

In [35]:
np.array([2, 3, 1])

array([2, 3, 1])

When two vectors of equal length are added, the elements are added point-wise.

$$
\begin{bmatrix} 2 \\ 3 \\ 1 \end{bmatrix} + \begin{bmatrix} 0 \\ 2 \\ -2 \end{bmatrix} = \begin{bmatrix} 2 \\ 5 \\ -1 \end{bmatrix}
$$


In [36]:
a = np.array([2, 3, 1])
b = np.array([0, 2, -2])
c = a + b
print(c)

[ 2  5 -1]


A vector can be multiplied element-wise by a number (called a "scalar"). For example:
    

$$
3 \begin{bmatrix} 2 \\ 3 \\ 1 \end{bmatrix} = \begin{bmatrix} 6 \\ 9 \\ 3 \end{bmatrix}
$$


A dot product is defined as the sum of the element-wise products of two equal-sized vectors. For two vectors $a$ and $b$, it is denoted as $a \cdot b$ or as $a b^T$ (where T refers to the transpose operation, introduced further down this notebook.

$$
\begin{bmatrix} 1 & -2 & 2 \end{bmatrix} \begin{bmatrix} 0 \\ 2 \\ 3 \end{bmatrix} = 2
$$

This can be calculated with the `numpy.dot` function:

In [57]:
a = np.array([1,-2,2])
b = np.array([0,2,3])
c = np.dot(a, b)
print(c)

2


## Matrices

A matrix is a rectangular array of numbers.

Numpy can create matrices from normal Python lists using `numpy.matrix`. For example:

In [37]:
np.matrix([[2,3,1],[0, 4,-2]])

matrix([[ 2,  3,  1],
        [ 0,  4, -2]])

To instantiate a matrix of all zeros:

In [38]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

To instantiate a matrix of all ones:

In [30]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In linear algebra, a square matrix whose elements are all zeros, except the diagonals, which are ones, is called an "identity matrix." 

For example:

$$
\mathbf I =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$$

is a 3x3 identity matrix. The reason why it is called an identity matrix is that it is analagous to multiplying a scalar by 1. A vector multiplied by an identity matrix is unchanged. 

$$
\mathbf I v = v
$$

To instantiate an identity matrix, use `numpy.eye`. For example:

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

To instantiate a matrix of random elements (between 0 and 1), you can use `numpy.random`:

In [44]:
A = np.random.random((2, 3))
print(A)

[[0.63870631 0.86963784 0.1836631 ]
 [0.04099372 0.59414384 0.61424414]]


Transposition is to reverse the axes of two matrices. So the element at `i,j` in the transposed matrix is equal to the element at `j,i` in the original. The matrix A transposed is denoted as $A^T$. 

In [48]:
A_transpose = np.transpose(A)
print(A_transpose)

[[0.63870631 0.04099372]
 [0.86963784 0.59414384]
 [0.1836631  0.61424414]]


It can also be done with the shorthand `.T` operation, as in:

In [49]:
A_transpose = A.T
print(A_transpose)

[[0.63870631 0.04099372]
 [0.86963784 0.59414384]
 [0.1836631  0.61424414]]


Like regular vectors, matrices are added point-wise (or element-wise) and must be of the same size. So for example:

$$
\begin{bmatrix} 4 & 3 \\ 3 & -1 \\ -2 & 1 \end{bmatrix} + \begin{bmatrix} -2 & 1 \\ 5 & 3 \\ 1 & 0 \end{bmatrix} = \begin{bmatrix} 2 & 4 \\ 8 & 2 \\ -1 & 1 \end{bmatrix} 
$$


In [50]:
a = np.matrix([[4, 3],[3,-1],[-2,1]])
b = np.matrix([[-2, 1],[5,3],[1,0]])
c = a + b
print(c)

[[ 2  4]
 [ 8  2]
 [-1  1]]


Also like vectors, matrices can be multiplied element-wise by a scalar.

$$
-2 \begin{bmatrix} 1 & -2 & 0 \\ 6 & 4 & -2 \end{bmatrix} = \begin{bmatrix} -2 & 4 & 0 \\ -12 & -8 & 4 \end{bmatrix} 
$$


In [51]:
a = np.matrix([[1,-2,0],[6,4,-2]])
-2 * a

matrix([[ -2,   4,   0],
        [-12,  -8,   4]])

To multiply two matrices together, you take the dot product of each row of the first matrix and each column of the second matrix, as in:  

![matrix multiplication via wikipedia](https://wikimedia.org/api/rest_v1/media/math/render/svg/780671bdfb3fab93187156d2c226df6fe36746fe)

So in order to multiply matrices $A$ and $B$ together, as in $C = A \dot B$, $A$ must have the same number of columns as $B$ has rows. For example:


$$
\begin{bmatrix} 1 & -2 & 0 \\ 6 & 4 & -2 \end{bmatrix} * \begin{bmatrix} 4 & -1 \\ 0 & -2 \\ 1 & 3 \end{bmatrix} = \begin{bmatrix} 4 & 3 \\ 22 & -20 \end{bmatrix} 
$$


In [55]:
a = np.matrix([[1,-2,0],[6,4,-2]])
b = np.matrix([[4,-1],[0,-2],[1,3]])
c = a * b
print(c)

[[  4   3]
 [ 22 -20]]


The Hadamard product of two matrices differs from normal multiplication in that it is the element-wise multiplication of two matrices. 

$$
\mathbf A \odot B =
\begin{bmatrix}
A_{1,1} B_{1,1} & \dots & A_{1,n} B_{1,n} \\
\vdots & \dots & \vdots \\
A_{m,1} B_{m,1} & \dots & A_{m,n} B_{m,n}
\end{bmatrix}
$$

So for example:

$$
\begin{bmatrix} 3 & 1 \\ 0 & 5 \end{bmatrix} + \begin{bmatrix} -2 & 4 \\ 1 & -2 \end{bmatrix} = \begin{bmatrix} -6 & 4 \\ 0 & -10 \end{bmatrix} 
$$

To calculate this with numpy, simply instantiate the matrices with `numpy.array` instead of `numpy.matrix` and it will use element-wise multiplication by default.

In [53]:
a = np.array([[3,1],[0,5]])
b = np.array([[-2,4],[1,-2]])
np.multiply(a,b)

array([[ -6,   4],
       [  0, -10]])


calc
 - functions
 - limits
 - derivative
 - chain rule

grad
 - partial derivative
 - gradient